import {
  Siren,
  Waves,
  Flame,
  GitBranch,
  Droplets,
  Droplet,
  Zap,
  Gauge,
  Disc,
  Cog,
  Wind,
  CircleDot,
  Home,
  CloudLightning,
  Layers,
  Search,
  Scissors,
  PenTool,
  Leaf,
  Mountain,
  TreePine,
  ChefHat,
  Bath,
  Hammer,
  Wrench,
  Utensils,
  ShoppingBag,
  PartyPopper,
  Sparkles,
  UserRound,
  Baby,
  Palette,
  Shield,
  Sun,
  Anchor,
  HeartPulse,
  Plug,
  Lightbulb,
  BatteryCharging,
  Thermometer,
  Snowflake,
  Fan,
  KeyRound,
  Lock,
  Bug,
  Rat,
  SprayCan,
  Warehouse,
  DoorOpen,
  Fence,
  Truck,
  Trash2,
  Sofa,
  Axe,
  PaintRoller,
  Brush,
  Ruler,
  HardHat,
  Construction,
  Blocks,
  Drill,
  Tv,
  Package,
  ShieldCheck,
  Timer,
  Recycle,
  CircleParking,
  Wrench as WrenchAlt,
  Star,
  type LucideIcon,
} from "lucide-react";

const ICONS: Record<string, LucideIcon> = {
  siren: Siren,
  waves: Waves,
  flame: Flame,
  gitBranch: GitBranch,
  droplets: Droplets,
  droplet: Droplet,
  zap: Zap,
  gauge: Gauge,
  disc: Disc,
  cog: Cog,
  wind: Wind,
  circleDot: CircleDot,
  home: Home,
  cloudLightning: CloudLightning,
  layers: Layers,
  search: Search,
  scissors: Scissors,
  penTool: PenTool,
  leaf: Leaf,
  mountain: Mountain,
  treePine: TreePine,
  chefHat: ChefHat,
  bath: Bath,
  hammer: Hammer,
  wrench: Wrench,
  utensils: Utensils,
  shoppingBag: ShoppingBag,
  partyPopper: PartyPopper,
  sparkles: Sparkles,
  userRound: UserRound,
  baby: Baby,
  palette: Palette,
  shield: Shield,
  sun: Sun,
  anchor: Anchor,
  heartPulse: HeartPulse,
  plug: Plug,
  lightbulb: Lightbulb,
  batteryCharging: BatteryCharging,
  thermometer: Thermometer,
  snowflake: Snowflake,
  fan: Fan,
  keyRound: KeyRound,
  lock: Lock,
  bug: Bug,
  rat: Rat,
  sprayCan: SprayCan,
  warehouse: Warehouse,
  doorOpen: DoorOpen,
  fence: Fence,
  truck: Truck,
  trash: Trash2,
  sofa: Sofa,
  axe: Axe,
  paintRoller: PaintRoller,
  brush: Brush,
  ruler: Ruler,
  hardHat: HardHat,
  construction: Construction,
  blocks: Blocks,
  drill: Drill,
  tv: Tv,
  package: Package,
  shieldCheck: ShieldCheck,
  timer: Timer,
  recycle: Recycle,
  circleParking: CircleParking,
  wrenchAlt: WrenchAlt,
};

export function ServiceIcon({
  name,
  className,
  style,
}: {
  name?: string;
  className?: string;
  style?: React.CSSProperties;
}) {
  const Icon = (name && ICONS[name]) || Star;
  return <Icon className={className} style={style} strokeWidth={1.5} />;
}
